### ISSUE TITLE
Fails to load on node-red v0.13.4

### ISSUE THREAD

**Issue by renzenicolai** [2bbb/node-red-node-artnet#1]
```
6 Apr 21:42:11 - [info] Node-RED version: v0.13.4
6 Apr 21:42:11 - [info] Node.js  version: v5.10.0
6 Apr 21:42:11 - [info] Linux 4.4.5-1-ARCH x64 LE
6 Apr 21:42:11 - [info] Loading palette nodes
6 Apr 21:42:12 - [warn] ------------------------------------------
6 Apr 21:42:12 - [warn] [artnet] TypeError: Object.setPrototypeOf called on null or undefined
6 Apr 21:42:12 - [warn] ------------------------------------------
```

**Comment by robbie77566** [comment]
I am also getting this error and it doesn't load the module.  Is there anyone supporting this node?

**Comment by 2bbb** [comment]
@rnplus @robbie78738 
thanks issue and sorry for late replay.

i have not use node-red v0.13.4 yet.
and now, i don't have environment for testing artnet what i can use immediately...

if i will get a time and test env then i will fix it.

but, maybe problem is simple.
because this and "artnet-node" packages are simple.
and these is open.
let's read source and maybe you can fix it yourself. :)

**Comment by 2bbb** [comment]
in node v6,
artnet-node got error.

```
> artnet = require('artnet-node');
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at Object.exports.inherits (util.js:900:10)
    at Object.<anonymous> (/Users/2bit/Documents/Program/node/node_modules/artnet-node/lib/artnet_server.js:47:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by 2bbb** [comment]
on node v6, artnet-node got error.

```
> artnet = require('artnet-node');
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at Object.exports.inherits (util.js:900:10)
    at Object.<anonymous> (.../node_modules/artnet-node/lib/artnet_server.js:47:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by 2bbb** [comment]
@rnplus @robbie78738 
maybe now it works with [fix_artnet_node branch](https://github.com/2bbb/node-red-node-artnet/tree/dev/fix_artnet_node)
but, i can't test real environment.

please try it.
and, if works correclty, then please tell me! :)

**Comment by 2bbb** [comment]
@rnplus @robbie78738 
how is it?

**Comment by Noir-** [comment]
Hi, are you still caring about this node? I got the same error but your branch seems not to fix the error. I'd love to see it working!

**Comment by 2bbb** [comment]
@Noir- 

mmm...

i can't get same error.

and now, i did update latest version.
could you try on latest versions?

```
11 Jan 22:52:40 - [info] Node-RED version: v0.15.3-git
11 Jan 22:52:40 - [info] Node.js  version: v6.9.2
11 Jan 22:52:40 - [info] Darwin 16.3.0 x64 LE
11 Jan 22:52:40 - [info] Loading palette nodes
11 Jan 22:52:40 - [warn] ------------------------------------------------------
11 Jan 22:52:40 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
11 Jan 22:52:40 - [warn] ------------------------------------------------------
```
